/* This file was autogenerated. All changes will be undone. */

/* Message: Ping, ID: 0002*/

#include <comnet_marshal.h>
#include <comnet_message.h>
#include <message/Ping.h>

msg_offset pack_ping(
   ping_t* ping,
   msg_offset offset)
{
   offset = pack_float64_t(ping->timestamp,offset);
   return offset;
}

msg_offset unpack_ping(
   msg_offset offset,
   ping_t* out_ptr)
{
   offset = unpack_float64_t(offset, &out_ptr->timestamp);
   return offset;
}

void com_ping(
   uint8_t src_id,
   uint8_t dest_id,
   ping_t* tx_msg,
   com_msg_t* msg)


{
   msg_offset start_offset, offset;
   msg->direction = Com_Out;
   start_offset = msg->data;
   offset = msg->data;
   msg->header.node_src_id = src_id;
   msg->header.node_dest_id = dest_id;
   msg->header.message_length = 8;
   msg->header.message_type = Com_Ping;
   offset = pack_sync(offset);
   offset = pack_header(&msg->header, offset);

   offset = pack_ping(tx_msg, offset);
   offset = pack_checksum(start_offset, offset);
   msg->tx_len = offset-start_offset;
}