/**@file This file was autogenerated. All changes will be undone. */

/** Message: Communications_Payload_Status, ID: 4003*/

#ifndef _COMMUNICATIONS_PAYLOAD_STATUS_H_
#define _COMMUNICATIONS_PAYLOAD_STATUS_H_

#include <comnet_marshal.h>
#include <comnet_message.h>

#include"random_numbers.h"
#include "aes.h"
using CryptoPP::AES;
#include "ccm.h"
using CryptoPP::CFB_Mode;
typedef struct {
   float64_t timestamp;
   uint16_t communications_ID;
   uint8_t communications_mode;
   uint8_t communications_status;
} communications_payload_status_t;

msg_offset pack_communications_payload_status(
   communications_payload_status_t* communications_payload_status,
   msg_offset offset);

msg_offset unpack_communications_payload_status(
   msg_offset offset,
   communications_payload_status_t* out_ptr);

void encode_communications_payload_status(
   uint8_t src_id,
   uint8_t dest_id,
   communications_payload_status_t* tx_msg,
   com_msg_t* msg,
   uint8_t keyArr[]);//key for encryption CryptoPP

#endif