/**@file This file was autogenerated. All changes will be undone. */

/** Message: Connection_Reply, ID: 0006*/

#ifndef _CONNECTION_REPLY_H_
#define _CONNECTION_REPLY_H_

#include <comnet_marshal.h>
#include <comnet_message.h>

#include"random_numbers.h"
#include "aes.h"
using CryptoPP::AES;
#include "ccm.h"
using CryptoPP::CFB_Mode;
typedef struct {
   float64_t timestamp;
   uint8_t connection_ID;
   uint8_t trace_node_n;
   uint8_t trace_node_n_1;
} connection_reply_t;

msg_offset pack_connection_reply(
   connection_reply_t* connection_reply,
   msg_offset offset);

msg_offset unpack_connection_reply(
   msg_offset offset,
   connection_reply_t* out_ptr);

void encode_connection_reply(
   uint8_t src_id,
   uint8_t dest_id,
   connection_reply_t* tx_msg,
   com_msg_t* msg,
   uint8_t keyArr[]);//key for encryption CryptoPP

#endif