/**@file This file was autogenerated. All changes will be undone. */

/** Message: Connection_Request, ID: 0005*/

#ifndef _CONNECTION_REQUEST_H_
#define _CONNECTION_REQUEST_H_

#include <comnet_marshal.h>
#include <comnet_message.h>

#include"random_numbers.h"
#include "aes.h"
using CryptoPP::AES;
#include "ccm.h"
using CryptoPP::CFB_Mode;
typedef struct {
   float64_t timestamp;
   uint8_t trace_node_1;
   uint8_t trace_node_n;
} connection_request_t;

msg_offset pack_connection_request(
   connection_request_t* connection_request,
   msg_offset offset);

msg_offset unpack_connection_request(
   msg_offset offset,
   connection_request_t* out_ptr);

void encode_connection_request(
   uint8_t src_id,
   uint8_t dest_id,
   connection_request_t* tx_msg,
   com_msg_t* msg,
   uint8_t keyArr[]);//key for encryption CryptoPP

#endif