/**@file This file was autogenerated. All changes will be undone. */

/** Message: Enter, ID: 0000*/

#ifndef _ENTER_H_
#define _ENTER_H_

#include <comnet_marshal.h>
#include <comnet_message.h>

#include"random_numbers.h"
#include "aes.h"
using CryptoPP::AES;
#include "ccm.h"
using CryptoPP::CFB_Mode;
typedef struct {
   float64_t timestamp;
} enter_t;

msg_offset pack_enter(
   enter_t* enter,
   msg_offset offset);

msg_offset unpack_enter(
   msg_offset offset,
   enter_t* out_ptr);

void encode_enter(
   uint8_t src_id,
   uint8_t dest_id,
   uint8_t msg_ttl,
   uint8_t seq_number,
   enter_t* tx_msg,
   com_msg_t* msg,
   uint8_t keyArr[]);//key for encryption CryptoPP

#endif