/**@file This file was autogenerated. All changes will be undone. */

/** Message: Payload_Bay_Mode_Command, ID: 3005*/

#ifndef _PAYLOAD_BAY_MODE_COMMAND_H_
#define _PAYLOAD_BAY_MODE_COMMAND_H_

#include <comnet_marshal.h>
#include <comnet_message.h>

#include"random_numbers.h"
#include "aes.h"
using CryptoPP::AES;
#include "ccm.h"
using CryptoPP::CFB_Mode;
typedef struct {
   float64_t timestamp;
   uint16_t payload_ID;
   uint8_t payload_mode;
} payload_bay_mode_command_t;

msg_offset pack_payload_bay_mode_command(
   payload_bay_mode_command_t* payload_bay_mode_command,
   msg_offset offset);

msg_offset unpack_payload_bay_mode_command(
   msg_offset offset,
   payload_bay_mode_command_t* out_ptr);

void encode_payload_bay_mode_command(
   uint8_t src_id,
   uint8_t dest_id,
   payload_bay_mode_command_t* tx_msg,
   com_msg_t* msg,
   uint8_t keyArr[]);//key for encryption CryptoPP

#endif