/**@file This file was autogenerated. All changes will be undone. */

/** Message: Raw_Data, ID: 0004*/

#ifndef _RAW_DATA_H_
#define _RAW_DATA_H_

#include <comnet_marshal.h>
#include <comnet_message.h>

#include"random_numbers.h"
#include "aes.h"
using CryptoPP::AES;
#include "ccm.h"
using CryptoPP::CFB_Mode;
typedef struct {
   float64_t timestamp;
   uint16_t length;
   uint8_t data;
} raw_data_t;

msg_offset pack_raw_data(
   raw_data_t* raw_data,
   msg_offset offset);

msg_offset unpack_raw_data(
   msg_offset offset,
   raw_data_t* out_ptr);

void encode_raw_data(
   uint8_t src_id,
   uint8_t dest_id,
   raw_data_t* tx_msg,
   com_msg_t* msg,
   uint8_t keyArr[]);//key for encryption CryptoPP

#endif