/**@file This file was autogenerated. All changes will be undone. */

/** Message: ROV_Status_Message, ID: 9001*/

#ifndef _ROV_STATUS_MESSAGE_H_
#define _ROV_STATUS_MESSAGE_H_

#include <comnet_marshal.h>
#include <comnet_message.h>

#include"random_numbers.h"
#include "aes.h"
using CryptoPP::AES;
#include "ccm.h"
using CryptoPP::CFB_Mode;
typedef struct {
   float64_t timestamp;
   uint16_t vehicle_ID;
   uint16_t depth;
   uint16_t roll;
   uint16_t pitch;
   uint16_t heading;
   float32_t battery_percent;
} ROV_status_message_t;

msg_offset pack_ROV_status_message(
   ROV_status_message_t* ROV_status_message,
   msg_offset offset);

msg_offset unpack_ROV_status_message(
   msg_offset offset,
   ROV_status_message_t* out_ptr);

void encode_ROV_status_message(
   uint8_t src_id,
   uint8_t dest_id,
   ROV_status_message_t* tx_msg,
   com_msg_t* msg,
   uint8_t keyArr[]);//key for encryption CryptoPP

#endif