/**@file This file was autogenerated. All changes will be undone. */

/** Message: Target_Status, ID: 5000*/

#ifndef _TARGET_STATUS_H_
#define _TARGET_STATUS_H_

#include <comnet_marshal.h>
#include <comnet_message.h>

#include"random_numbers.h"
#include "aes.h"
using CryptoPP::AES;
#include "ccm.h"
using CryptoPP::CFB_Mode;
typedef struct {
   float64_t timestamp;
   float64_t target_radius;
   float64_t target_angle;
   float64_t target_altitude;
} target_status_t;

msg_offset pack_target_status(
   target_status_t* target_status,
   msg_offset offset);

msg_offset unpack_target_status(
   msg_offset offset,
   target_status_t* out_ptr);

void encode_target_status(
   uint8_t src_id,
   uint8_t dest_id,
   target_status_t* tx_msg,
   com_msg_t* msg,
   uint8_t keyArr[]);//key for encryption CryptoPP

#endif