/**@file This file was autogenerated. All changes will be undone. */

/** Message: UAV_Battery, ID: 6003*/

#ifndef _UAV_BATTERY_H_
#define _UAV_BATTERY_H_

#include <comnet_marshal.h>
#include <comnet_message.h>

#include"random_numbers.h"
#include "aes.h"
using CryptoPP::AES;
#include "ccm.h"
using CryptoPP::CFB_Mode;
typedef struct {
   float64_t timestamp;
   uint32_t battery_percentage;
} UAV_battery_t;

msg_offset pack_UAV_battery(
   UAV_battery_t* UAV_battery,
   msg_offset offset);

msg_offset unpack_UAV_battery(
   msg_offset offset,
   UAV_battery_t* out_ptr);

void encode_UAV_battery(
   uint8_t src_id,
   uint8_t dest_id,
   UAV_battery_t* tx_msg,
   com_msg_t* msg,
   uint8_t keyArr[]);//key for encryption CryptoPP

#endif