/**@file This file was autogenerated. All changes will be undone. */

/** Message: UGV_Battery_Status, ID: 6001*/

#ifndef _UGV_BATTERY_STATUS_H_
#define _UGV_BATTERY_STATUS_H_

#include <comnet_marshal.h>
#include <comnet_message.h>

#include"random_numbers.h"
#include "aes.h"
using CryptoPP::AES;
#include "ccm.h"
using CryptoPP::CFB_Mode;
typedef struct {
   float64_t timestamp;
   float32_t voltage_3_3V;
   float32_t voltage_5V;
   float32_t voltage_12V;
   float32_t current_3_3V;
   float32_t current_5V;
   float32_t current_12V;
   float32_t current_fore_motor;
   float32_t current_aft_motor;
} UGV_battery_status_t;

msg_offset pack_UGV_battery_status(
   UGV_battery_status_t* UGV_battery_status,
   msg_offset offset);

msg_offset unpack_UGV_battery_status(
   msg_offset offset,
   UGV_battery_status_t* out_ptr);

void encode_UGV_battery_status(
   uint8_t src_id,
   uint8_t dest_id,
   UGV_battery_status_t* tx_msg,
   com_msg_t* msg,
   uint8_t keyArr[]);//key for encryption CryptoPP

#endif