/**@file This file was autogenerated. All changes will be undone. */

/** Message: Vehicle_System_Status, ID: 2000*/

#ifndef _VEHICLE_SYSTEM_STATUS_H_
#define _VEHICLE_SYSTEM_STATUS_H_

#include <comnet_marshal.h>
#include <comnet_message.h>

typedef struct {
   float64_t timestamp;
   uint16_t vehicle_ID;
   uint8_t vehicle_mode;
   uint8_t vehicle_state;
} vehicle_system_status_t;

msg_offset pack_vehicle_system_status(
   vehicle_system_status_t* vehicle_system_status,
   msg_offset offset);

msg_offset unpack_vehicle_system_status(
   msg_offset offset,
   vehicle_system_status_t* out_ptr);

void com_vehicle_system_status(
   uint8_t src_id,
   uint8_t dest_id,
   vehicle_system_status_t* tx_msg,
   com_msg_t* msg);
#endif