/* This file was autogenerated. All changes will be undone. */

/* Message: Target_Designation_Command, ID: 5000*/

#include <protonet_marshal.h>
#include <protonet_message.h>
#include <message/TargetDesignationCommand.h>

msg_offset pack_target_designation_command(
   target_designation_command_t* target_designation_command,
   msg_offset offset)
{
   offset = pack_float64_t(target_designation_command->timestamp,offset);
   offset = pack_uint16_t(target_designation_command->vehicle_ID,offset);
   offset = pack_uint8_t(target_designation_command->payload_ID,offset);
   offset = pack_uint8_t(target_designation_command->target_ID,offset);
   offset = pack_uint8_t(target_designation_command->target_type,offset);
   offset = pack_int32_t(target_designation_command->latitude,offset);
   offset = pack_int32_t(target_designation_command->longitude,offset);
   offset = pack_int32_t(target_designation_command->altitude,offset);
   return offset;
}

msg_offset unpack_target_designation_command(
   msg_offset offset,
   target_designation_command_t* out_ptr)
{
   offset = unpack_float64_t(offset, &out_ptr->timestamp);
   offset = unpack_uint16_t(offset, &out_ptr->vehicle_ID);
   offset = unpack_uint8_t(offset, &out_ptr->payload_ID);
   offset = unpack_uint8_t(offset, &out_ptr->target_ID);
   offset = unpack_uint8_t(offset, &out_ptr->target_type);
   offset = unpack_int32_t(offset, &out_ptr->latitude);
   offset = unpack_int32_t(offset, &out_ptr->longitude);
   offset = unpack_int32_t(offset, &out_ptr->altitude);
   return offset;
}

void encode_target_designation_command(
   uint8_t src_id,
   uint8_t dest_id,
   uint8_t msg_ttl,
   uint8_t seq_number,
   target_designation_command_t* tx_msg,
   proto_msg_t* msg)
{
   msg_offset start_offset, offset;
   msg->direction = Proto_Out;
   start_offset = msg->data;
   offset = msg->data;
   msg->header.node_src_id = src_id;
   msg->header.node_dest_id = dest_id;
   msg->header.message_ttl = msg_ttl;
   msg->header.sequence_number = seq_number;
   msg->header.message_length = 25;
   msg->header.message_type = Proto_Target_Designation_Command;
   offset = pack_sync(offset);
   offset = pack_header(&msg->header, offset);
   offset = pack_target_designation_command(tx_msg, offset);
   offset = pack_checksum(start_offset, offset);
   msg->tx_len = offset-start_offset;
}